import {
  LastMinPrepCategory,
  LastMinPrepProgress,
  LastMinPrepQuestion,
} from './last-min-prep';

export type GooglePrepProgress = LastMinPrepProgress;

function q(leetcodeId: number, title: string, pattern: string, important?: boolean): LastMinPrepQuestion {
  return {
    leetcodeId,
    title,
    difficulty: 'Medium',
    category: 'Google Questions',
    pattern,
    important,
  };
}

export const GOOGLE_PREP_CATEGORIES: LastMinPrepCategory[] = [
  {
    id: 'google-questions',
    name: 'Google Questions',
    pattern: 'Curated Google-tagged list',
    questions: [
      q(295, 'Find Median from Data Stream', 'Two heaps', true),
      q(692, 'Top K Frequent Words', 'Heap'),
      q(228, 'Summary Ranges', 'Array scan'),
      q(205, 'Isomorphic Strings', 'Hash map'),
      q(221, 'Maximal Square', 'Grid DP', true),
      q(85, 'Maximal Rectangle', 'Monotonic stack'),
      q(346, 'Moving Average from Data Stream', 'Queue / sliding window'),
      q(53, 'Maximum Subarray', 'Kadane'),
      q(1834, 'Single-Threaded CPU', 'Heap simulation', true),
      q(200, 'Number of Islands', 'DFS / BFS'),
      q(208, 'Implement Trie (Prefix Tree)', 'Trie'),
      q(23, 'Merge k Sorted Lists', 'Heap / merge'),
      q(359, 'Logger Rate Limiter', 'Hash map'),
      q(2013, 'Detect Squares', 'Hash map'),
      q(2155, 'All Divisions With the Highest Score of a Binary Array', 'Prefix sum'),
      q(853, 'Car Fleet', 'Monotonic stack'),
      q(1776, 'Car Fleet II', 'Monotonic stack'),
      q(968, 'Binary Tree Cameras', 'Tree DP / greedy'),
      q(1791, 'Find Center of Star Graph', 'Graph'),
      q(146, 'LRU Cache', 'Design / hash + doubly linked list', true),
      q(307, 'Range Sum Query - Mutable', 'Segment tree / BIT'),
      q(986, 'Interval List Intersections', 'Two pointers'),
      q(939, 'Minimum Area Rectangle', 'Hash set'),
      q(963, 'Minimum Area Rectangle II', 'Geometry / hash'),
      q(2050, 'Parallel Courses III', 'Topological sort + DP'),
      q(1971, 'Find if Path Exists in Graph', 'Union Find / DFS'),
      q(33, 'Search in Rotated Sorted Array', 'Binary search'),
      q(261, 'Graph Valid Tree', 'Union Find / DFS'),
      q(402, 'Remove K Digits', 'Monotonic stack', true),
      q(17, 'Letter Combinations of a Phone Number', 'Backtracking'),
      q(1525, 'Number of Good Ways to Split a String', 'Prefix / suffix count'),
      q(772, 'Basic Calculator III', 'Stack'),
      q(715, 'Range Module', 'Segment tree / interval map', true),
      q(300, 'Longest Increasing Subsequence', '1D DP / LIS', true),
      q(1091, 'Shortest Path in Binary Matrix', 'BFS'),
      q(207, 'Course Schedule', 'Topological sort', true),
      q(1268, 'Search Suggestions System', 'Trie / sort'),
      q(485, 'Max Consecutive Ones', 'Array scan'),
      q(1004, 'Max Consecutive Ones III', 'Sliding window'),
      q(102, 'Binary Tree Level Order Traversal', 'Tree BFS'),
      q(75, 'Sort Colors', 'Dutch flag partition'),
      q(1155, 'Number of Dice Rolls With Target Sum', 'DP'),
      q(743, 'Network Delay Time', 'Dijkstra'),
      q(49, 'Group Anagrams', 'Hash map'),
      q(994, 'Rotting Oranges', 'Multi-source BFS'),
      q(253, 'Meeting Rooms II', 'Heap / sweep'),
      q(852, 'Peak Index in a Mountain Array', 'Binary search'),
      q(55, 'Jump Game', 'Greedy'),
      q(312, 'Burst Balloons', 'Interval DP'),
      q(704, 'Binary Search', 'Binary search'),
      q(209, 'Minimum Size Subarray Sum', 'Sliding window'),
      q(366, 'Find Leaves of Binary Tree', 'Tree DFS', true),
      q(1616, 'Split Two Strings to Make Palindrome', 'Two pointers'),
      q(1293, 'Shortest Path in a Grid with Obstacles Elimination', 'BFS + state', true),
      q(818, 'Race Car', 'BFS / DP'),
      q(1499, 'Max Value of Equation', 'Monotonic deque'),
      q(360, 'Sort Transformed Array', 'Two pointers'),
      q(282, 'Expression Add Operators', 'Backtracking'),
      q(947, 'Most Stones Removed with Same Row or Column', 'Union Find / DFS'),
      q(215, 'Kth Largest Element in an Array', 'Heap / quickselect'),
      q(863, 'All Nodes Distance K in Binary Tree', 'Tree-to-graph BFS'),
      q(518, 'Coin Change II', 'Unbounded knapsack'),
      q(1494, 'Parallel Courses II', 'Bitmask DP'),
      q(2402, 'Meeting Rooms III', 'Heap simulation'),
      q(2265, 'Count Nodes Equal to Average of Subtree', 'Tree DFS'),
      q(907, 'Sum of Subarray Minimums', 'Monotonic stack', true),
      q(337, 'House Robber III', 'Tree DP'),
      q(174, 'Dungeon Game', 'Grid DP (reverse)'),
      q(416, 'Partition Equal Subset Sum', '0/1 knapsack'),
      q(2035, 'Partition Array Into Two Arrays to Minimize Sum Difference', 'Meet in the middle'),
      q(315, 'Count of Smaller Numbers After Self', 'Merge sort / BIT'),
      q(128, 'Longest Consecutive Sequence', 'Hash set'),
      q(1011, 'Capacity To Ship Packages Within D Days', 'Binary search on answer'),
      q(1882, 'Process Tasks Using Servers', 'Heap simulation'),
      q(621, 'Task Scheduler', 'Greedy / heap'),
      q(759, 'Employee Free Time', 'Intervals / heap', true),
      q(56, 'Merge Intervals', 'Sort + merge', true),
      q(57, 'Insert Interval', 'Intervals'),
      q(435, 'Non-overlapping Intervals', 'Greedy'),
      q(236, 'Lowest Common Ancestor of a Binary Tree', 'Tree DFS'),
      q(2096, 'Step-By-Step Directions From a Binary Tree Node to Another', 'Tree DFS + LCA'),
      q(222, 'Count Complete Tree Nodes', 'Binary search on tree'),
      q(98, 'Validate Binary Search Tree', 'BST inorder'),
      q(230, 'Kth Smallest Element in a BST', 'BST inorder'),
      q(103, 'Binary Tree Zigzag Level Order Traversal', 'Tree BFS'),
      q(105, 'Construct Binary Tree from Preorder and Inorder Traversal', 'Tree DFS'),
      q(124, 'Binary Tree Maximum Path Sum', 'Tree DFS'),
      q(210, 'Course Schedule II', 'Topological sort', true),
      q(1462, 'Course Schedule IV', 'Topological sort'),
      q(1136, 'Parallel Courses', 'Topological sort', true),
      q(310, 'Minimum Height Trees', 'Topological / BFS trim'),
      q(684, 'Redundant Connection', 'Union Find'),
      q(547, 'Number of Provinces', 'DSU / DFS'),
      q(305, 'Number of Islands II', 'Union Find', true),
      q(721, 'Accounts Merge', 'Union Find'),
      q(399, 'Evaluate Division', 'Graph DFS / weighted union', true),
      q(2101, 'Detonate the Maximum Bombs', 'Graph DFS / BFS', true),
      q(787, 'Cheapest Flights Within K Stops', 'Bellman-Ford / Dijkstra'),
      q(127, 'Word Ladder', 'BFS on words'),
      q(133, 'Clone Graph', 'DFS / BFS'),
      q(785, 'Is Graph Bipartite?', 'Graph coloring'),
      q(802, 'Find Eventual Safe States', 'Topo / cycle detection'),
      q(332, 'Reconstruct Itinerary', 'Eulerian path'),
      q(1584, 'Min Cost to Connect All Points', 'MST'),
      q(695, 'Max Area of Island', 'DFS / BFS'),
      q(733, 'Flood Fill', 'DFS / BFS'),
      q(542, '01 Matrix', 'Multi-source BFS', true),
      q(417, 'Pacific Atlantic Water Flow', 'Multi-source DFS / BFS'),
      q(79, 'Word Search', 'Backtracking / DFS', true),
      q(130, 'Surrounded Regions', 'DFS / BFS'),
      q(1277, 'Count Square Submatrices with All Ones', 'Grid DP'),
      q(934, 'Shortest Bridge', 'DFS + BFS'),
      q(329, 'Longest Increasing Path in a Matrix', 'DFS + memo'),
      q(64, 'Minimum Path Sum', 'Grid DP'),
      q(62, 'Unique Paths', 'Grid DP'),
      q(63, 'Unique Paths II', 'Grid DP'),
      q(980, 'Unique Paths III', 'Backtracking'),
      q(480, 'Sliding Window Median', 'Two heaps / sorted list'),
      q(239, 'Sliding Window Maximum', 'Monotonic deque', true),
      q(347, 'Top K Frequent Elements', 'Heap / bucket sort'),
      q(973, 'K Closest Points to Origin', 'Heap'),
      q(703, 'Kth Largest Element in a Stream', 'Heap'),
      q(378, 'Kth Smallest Element in a Sorted Matrix', 'Heap / binary search'),
      q(373, 'Find K Pairs with Smallest Sums', 'Heap'),
      q(528, 'Random Pick with Weight', 'Prefix sum + binary search', true),
      q(398, 'Random Pick Index', 'Reservoir sampling'),
      q(380, 'Insert Delete GetRandom O(1)', 'Design / hash + array'),
      q(710, 'Random Pick with Blacklist', 'Hash remap'),
      q(384, 'Shuffle an Array', 'Fisher-Yates'),
      q(150, 'Evaluate Reverse Polish Notation', 'Stack', true),
      q(394, 'Decode String', 'Stack'),
      q(20, 'Valid Parentheses', 'Stack'),
      q(32, 'Longest Valid Parentheses', 'Stack / DP'),
      q(155, 'Min Stack', 'Design / stack'),
      q(84, 'Largest Rectangle in Histogram', 'Monotonic stack'),
      q(739, 'Daily Temperatures', 'Monotonic stack'),
      q(496, 'Next Greater Element I', 'Monotonic stack'),
      q(1554, 'Strings Differ by One Character', 'Hash map', true),
      q(187, 'Repeated DNA Sequences', 'Hash set / rolling hash', true),
      q(409, 'Longest Palindrome', 'Frequency map'),
      q(5, 'Longest Palindromic Substring', 'Expand around center'),
      q(720, 'Longest Word in Dictionary', 'Trie / sort', true),
      q(2437, 'Number of Valid Clock Times', 'Brute force / counting', true),
      q(3, 'Longest Substring Without Repeating Characters', 'Sliding window'),
      q(76, 'Minimum Window Substring', 'Sliding window'),
      q(983, 'Minimum Cost For Tickets', '1D DP', true),
      q(2172, 'Maximum AND Sum of Array', 'Bitmask DP', true),
      q(698, 'Partition to K Equal Sum Subsets', 'Backtracking + bitmask'),
      q(473, 'Matchsticks to Square', 'Backtracking'),
      q(365, 'Water and Jug Problem', 'Math / GCD', true),
      q(322, 'Coin Change', 'Unbounded knapsack'),
      q(494, 'Target Sum', 'Subset DP'),
      q(707, 'Design Linked List', 'Design / linked list'),
      q(432, 'All O`one Data Structure', 'Design / doubly linked list'),
      q(34, 'Find First and Last Position of Element in Sorted Array', 'Binary search', true),
      q(1150, 'Check If a Number Is Majority Element in a Sorted Array', 'Binary search', true),
      q(153, 'Find Minimum in Rotated Sorted Array', 'Binary search'),
    ],
  },
];

export function getAllGooglePrepQuestions(): LastMinPrepQuestion[] {
  return GOOGLE_PREP_CATEGORIES.flatMap((c) => c.questions);
}

const STORAGE_PREFIX = 'google_prep_';

function storageKey(userId: string): string {
  return `${STORAGE_PREFIX}${userId}`;
}

export function loadGooglePrepProgress(userId: string): GooglePrepProgress[] {
  if (typeof window === 'undefined') return [];
  try {
    return JSON.parse(localStorage.getItem(storageKey(userId)) || '[]');
  } catch {
    return [];
  }
}

export function saveGooglePrepProgress(userId: string, rows: GooglePrepProgress[]): void {
  if (typeof window === 'undefined') return;
  localStorage.setItem(storageKey(userId), JSON.stringify(rows));
}
