import {
  LastMinPrepCategory,
  LastMinPrepProgress,
  LastMinPrepQuestion,
} from './last-min-prep';

export type GooglePrepProgress = LastMinPrepProgress;

function q(leetcodeId: number, title: string, important?: boolean): LastMinPrepQuestion {
  return {
    leetcodeId,
    title,
    difficulty: 'Medium',
    category: 'Google Questions',
    pattern: '',
    important,
  };
}

export const GOOGLE_PREP_CATEGORIES: LastMinPrepCategory[] = [
  {
    id: 'google-questions',
    name: 'Google Questions',
    pattern: 'Curated Google-tagged list',
    questions: [
      q(295, 'Find Median from Data Stream', true),
      q(692, 'Top K Frequent Words'),
      q(228, 'Summary Ranges'),
      q(205, 'Isomorphic Strings'),
      q(221, 'Maximal Square', true),
      q(85, 'Maximal Rectangle'),
      q(346, 'Moving Average from Data Stream'),
      q(53, 'Maximum Subarray'),
      q(1834, 'Single-Threaded CPU', true),
      q(200, 'Number of Islands'),
      q(208, 'Implement Trie (Prefix Tree)'),
      q(23, 'Merge k Sorted Lists'),
      q(359, 'Logger Rate Limiter'),
      q(2013, 'Detect Squares'),
      q(2155, 'All Divisions With the Highest Score of a Binary Array'),
      q(853, 'Car Fleet'),
      q(1776, 'Car Fleet II'),
      q(968, 'Binary Tree Cameras'),
      q(1791, 'Find Center of Star Graph'),
      q(146, 'LRU Cache', true),
      q(307, 'Range Sum Query - Mutable'),
      q(986, 'Interval List Intersections'),
      q(939, 'Minimum Area Rectangle'),
      q(963, 'Minimum Area Rectangle II'),
      q(2050, 'Parallel Courses III'),
      q(1971, 'Find if Path Exists in Graph'),
      q(33, 'Search in Rotated Sorted Array'),
      q(261, 'Graph Valid Tree'),
      q(402, 'Remove K Digits', true),
      q(17, 'Letter Combinations of a Phone Number'),
      q(1525, 'Number of Good Ways to Split a String'),
      q(772, 'Basic Calculator III'),
      q(715, 'Range Module', true),
      q(300, 'Longest Increasing Subsequence', true),
      q(1091, 'Shortest Path in Binary Matrix'),
      q(207, 'Course Schedule', true),
      q(1268, 'Search Suggestions System'),
      q(485, 'Max Consecutive Ones'),
      q(1004, 'Max Consecutive Ones III'),
      q(102, 'Binary Tree Level Order Traversal'),
      q(75, 'Sort Colors'),
      q(1155, 'Number of Dice Rolls With Target Sum'),
      q(743, 'Network Delay Time'),
      q(49, 'Group Anagrams'),
      q(994, 'Rotting Oranges'),
      q(253, 'Meeting Rooms II'),
      q(852, 'Peak Index in a Mountain Array'),
      q(55, 'Jump Game'),
      q(312, 'Burst Balloons'),
      q(704, 'Binary Search'),
      q(209, 'Minimum Size Subarray Sum'),
      q(366, 'Find Leaves of Binary Tree', true),
      q(1616, 'Split Two Strings to Make Palindrome'),
      q(1293, 'Shortest Path in a Grid with Obstacles Elimination', true),
      q(818, 'Race Car'),
      q(1499, 'Max Value of Equation'),
      q(360, 'Sort Transformed Array'),
      q(282, 'Expression Add Operators'),
      q(947, 'Most Stones Removed with Same Row or Column'),
      q(215, 'Kth Largest Element in an Array'),
      q(863, 'All Nodes Distance K in Binary Tree'),
      q(518, 'Coin Change II'),
      q(1494, 'Parallel Courses II'),
      q(2402, 'Meeting Rooms III'),
      q(2265, 'Count Nodes Equal to Average of Subtree'),
      q(907, 'Sum of Subarray Minimums', true),
      q(337, 'House Robber III'),
      q(174, 'Dungeon Game'),
      q(416, 'Partition Equal Subset Sum'),
      q(2035, 'Partition Array Into Two Arrays to Minimize Sum Difference'),
      q(315, 'Count of Smaller Numbers After Self'),
      q(128, 'Longest Consecutive Sequence'),
      q(1011, 'Capacity To Ship Packages Within D Days'),
      q(1882, 'Process Tasks Using Servers'),
      q(621, 'Task Scheduler'),
      q(759, 'Employee Free Time', true),
      q(56, 'Merge Intervals', true),
      q(57, 'Insert Interval'),
      q(435, 'Non-overlapping Intervals'),
      q(236, 'Lowest Common Ancestor of a Binary Tree'),
      q(2096, 'Step-By-Step Directions From a Binary Tree Node to Another'),
      q(222, 'Count Complete Tree Nodes'),
      q(98, 'Validate Binary Search Tree'),
      q(230, 'Kth Smallest Element in a BST'),
      q(103, 'Binary Tree Zigzag Level Order Traversal'),
      q(105, 'Construct Binary Tree from Preorder and Inorder Traversal'),
      q(124, 'Binary Tree Maximum Path Sum'),
      q(210, 'Course Schedule II', true),
      q(1462, 'Course Schedule IV'),
      q(1136, 'Parallel Courses', true),
      q(310, 'Minimum Height Trees'),
      q(684, 'Redundant Connection'),
      q(547, 'Number of Provinces'),
      q(305, 'Number of Islands II', true),
      q(721, 'Accounts Merge'),
      q(399, 'Evaluate Division', true),
      q(2101, 'Detonate the Maximum Bombs', true),
      q(787, 'Cheapest Flights Within K Stops'),
      q(127, 'Word Ladder'),
      q(133, 'Clone Graph'),
      q(785, 'Is Graph Bipartite?'),
      q(802, 'Find Eventual Safe States'),
      q(332, 'Reconstruct Itinerary'),
      q(1584, 'Min Cost to Connect All Points'),
      q(695, 'Max Area of Island'),
      q(733, 'Flood Fill'),
      q(542, '01 Matrix', true),
      q(417, 'Pacific Atlantic Water Flow'),
      q(79, 'Word Search', true),
      q(130, 'Surrounded Regions'),
      q(1277, 'Count Square Submatrices with All Ones'),
      q(934, 'Shortest Bridge'),
      q(329, 'Longest Increasing Path in a Matrix'),
      q(64, 'Minimum Path Sum'),
      q(62, 'Unique Paths'),
      q(63, 'Unique Paths II'),
      q(980, 'Unique Paths III'),
      q(480, 'Sliding Window Median'),
      q(239, 'Sliding Window Maximum', true),
      q(347, 'Top K Frequent Elements'),
      q(973, 'K Closest Points to Origin'),
      q(703, 'Kth Largest Element in a Stream'),
      q(378, 'Kth Smallest Element in a Sorted Matrix'),
      q(373, 'Find K Pairs with Smallest Sums'),
      q(528, 'Random Pick with Weight', true),
      q(398, 'Random Pick Index'),
      q(380, 'Insert Delete GetRandom O(1)'),
      q(710, 'Random Pick with Blacklist'),
      q(384, 'Shuffle an Array'),
      q(150, 'Evaluate Reverse Polish Notation', true),
      q(394, 'Decode String'),
      q(20, 'Valid Parentheses'),
      q(32, 'Longest Valid Parentheses'),
      q(155, 'Min Stack'),
      q(84, 'Largest Rectangle in Histogram'),
      q(739, 'Daily Temperatures'),
      q(496, 'Next Greater Element I'),
      q(1554, 'Strings Differ by One Character', true),
      q(187, 'Repeated DNA Sequences', true),
      q(409, 'Longest Palindrome'),
      q(5, 'Longest Palindromic Substring'),
      q(720, 'Longest Word in Dictionary', true),
      q(2437, 'Number of Valid Clock Times', true),
      q(3, 'Longest Substring Without Repeating Characters'),
      q(76, 'Minimum Window Substring'),
      q(983, 'Minimum Cost For Tickets', true),
      q(2172, 'Maximum AND Sum of Array', true),
      q(698, 'Partition to K Equal Sum Subsets'),
      q(473, 'Matchsticks to Square'),
      q(365, 'Water and Jug Problem', true),
      q(322, 'Coin Change'),
      q(494, 'Target Sum'),
      q(707, 'Design Linked List'),
      q(432, 'All O`one Data Structure'),
      q(34, 'Find First and Last Position of Element in Sorted Array', true),
      q(1150, 'Check If a Number Is Majority Element in a Sorted Array', true),
      q(153, 'Find Minimum in Rotated Sorted Array'),
    ],
  },
];

export function getAllGooglePrepQuestions(): LastMinPrepQuestion[] {
  return GOOGLE_PREP_CATEGORIES.flatMap((c) => c.questions);
}

const STORAGE_PREFIX = 'google_prep_';

function storageKey(userId: string): string {
  return `${STORAGE_PREFIX}${userId}`;
}

export function loadGooglePrepProgress(userId: string): GooglePrepProgress[] {
  if (typeof window === 'undefined') return [];
  try {
    return JSON.parse(localStorage.getItem(storageKey(userId)) || '[]');
  } catch {
    return [];
  }
}

export function saveGooglePrepProgress(userId: string, rows: GooglePrepProgress[]): void {
  if (typeof window === 'undefined') return;
  localStorage.setItem(storageKey(userId), JSON.stringify(rows));
}
